version: '3.8'

services:
  openldap:
    image: docker.io/bitnami/openldap:2.6
    ports:
      - '1389:1389'
      - '1636:1636'
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=EC1234
      - LDAP_ROOT=dc=cec,dc=eu,dc=int
      - BITNAMI_DEBUG=true
    volumes: 
      - 'openldap_data:/bitnami/openldap'
      - './imports/ldifs:/ldifs'
      - './imports/schema/cudperson.ldif:/schema/custom.ldif'
    networks:
      - docker_eusurvey-network
volumes:
  openldap_data:
    driver: local
networks:
  docker_eusurvey-network:
    external: true