version: '3.8'
services:
  eusurvey-mysql:
    container_name: eusurvey-mysql
    image: 'bitnami/mysql:8.0.37-debian-12-r2'
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - eusurvey-mysql-data:/bitnami/mysql/data
      - ./mysql/init-db/:/docker-entrypoint-initdb.d/
      - ./mysql/my.cnf:/opt/bitnami/mysql/conf/my_custom.cnf  
    networks:
      - eusurvey-network

  eusurvey-tomcat:
    container_name: eusurvey-tomcat
    build: server
    image: eusurvey-tomcat:latest
    ports:
      - '8080:8080'
    environment:
      - JAVA_OPTS= "-Djava.awt.headless=true"
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - eusurvey-temp:/eusurveytemp/
    networks:
      - eusurvey-network   
volumes:
  eusurvey-mysql-data:
  eusurvey-temp:
    driver: local 

networks:
  eusurvey-network:
    driver: bridge 