DELIMITER $$

CREATE PROCEDURE `initInvitations` ()
BEGIN
	DECLARE done INT DEFAULT FALSE;
	DECLARE pid INT;	
	DECLARE pnum INT;
    DECLARE counter INT;

	DECLARE cur1 CURSOR FOR SELECT PARTICIPATION_ID FROM PARTICIPANTS;
	
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = TRUE;

	OPEN cur1;

	SET counter = 1;

	read_loop2: LOOP

		FETCH cur1 INTO pid;
		IF done THEN
		  LEAVE read_loop2;
		END IF;

		SELECT count(*) FROM INVITATIONS WHERE PARTICIPATIONGROUP_ID = pid INTO pnum;

		IF (pnum > 0) THEN
			UPDATE PARTICIPANTS SET PARTICIPATION_INVITED = pnum WHERE PARTICIPATION_ID = pid;
		END IF;	
		
		SELECT count(*) FROM INVITATIONS WHERE PARTICIPATIONGROUP_ID = pid AND INV_DEACTIVATED = 1 INTO pnum;

		IF (pnum > 0) THEN
			UPDATE PARTICIPANTS SET PARTICIPATION_INVITED_DEAC = pnum WHERE PARTICIPATION_ID = pid;
		END IF;	

		SET counter = counter + 1;

	END LOOP;

	CLOSE cur1;

	SELECT counter;
END

