DELIMITER $$

CREATE PROCEDURE `updateStatistics` (id int)
BEGIN
	DECLARE done INT DEFAULT FALSE;
	DECLARE pqid INT;	
	DECLARE ppaid INT;
	DECLARE pnum INT;
    DECLARE counter INT;

	DECLARE cur1 CURSOR FOR SELECT PA_ID, QUESTION_ID FROM ANSWERS WHERE AS_ID IN 
		(SELECT DISTINCT ANSWER_SET_ID FROM ANSWERS_SET WHERE SURVEY_ID = id AND ISDRAFT = 0);
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = TRUE;

	OPEN cur1;

	SET counter = 1;

	read_loop2: LOOP

		FETCH cur1 INTO ppaid,pqid;
		IF done THEN
		  LEAVE read_loop2;
		END IF;

		SELECT MAX(PAID) FROM LIVESTATISTICS WHERE PAID = ppaid AND QID = pqid INTO pnum;

		IF (pnum IS NOT NULL) THEN
			UPDATE LIVESTATISTICS SET NUM = NUM + 1 WHERE PAID = ppaid AND QID = pqid;
		ELSE
			INSERT INTO LIVESTATISTICS (PAID, QID, NUM) VALUES (ppaid, pqid, 1);
		END IF;	

		SET counter = counter + 1;

	END LOOP;

	CLOSE cur1;

	SELECT counter;
END

CREATE PROCEDURE `clearStatistics` (id int)
BEGIN
	DECLARE done INT DEFAULT FALSE;
	DECLARE pqid INT;	
	DECLARE ppaid INT;
	DECLARE counter INT;

	DECLARE cur1 CURSOR FOR SELECT PA_ID, QUESTION_ID FROM ANSWERS WHERE AS_ID IN 
		(SELECT DISTINCT ANSWER_SET_ID FROM ANSWERS_SET WHERE SURVEY_ID = id);
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = TRUE;

	OPEN cur1;

	SET counter = 1;

	read_loop2: LOOP

		FETCH cur1 INTO ppaid,pqid;
		IF done THEN
		  LEAVE read_loop2;
		END IF;
		
		DELETE FROM LIVESTATISTICS WHERE PAID = ppaid AND QID = pqid;

		SET counter = counter + 1;

	END LOOP;

	CLOSE cur1;

	SELECT counter;
END
